data_f <- read.table("household_power_consumption.txt", col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), sep = ";", header = TRUE, na.strings = "?", check.names = FALSE, stringsAsFactors = FALSE)
data_f$Date <- as.Date(data_f$Date, format = "%d/%m/%Y")
data <- subset(data_f, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(data_f)
data$datetime <- as.POSIXct(paste(as.Date(data$Date), data$Time))
par(mfrow = c(2,2), mar = c(4,4,2,1), oma = c(0,0,2,0))
plot(data$datetime, data$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(data$datetime, data$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(data$Sub_metering_1 ~ data$datetime, type = "l", ylab = "Energy sub metering", xlab = "")
lines(data$Sub_metering_2 ~ data$datetime, col = 'red')
lines(data$Sub_metering_3 ~ data$datetime, col = 'blue')
legend("topright", lty = 1, bty = "n", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(data$datetime, data$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.copy(png, file = "plot4.png")
dev.off()